name: ci/gh-actions/cli

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  build-ios:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build.
      run: |
        brew install llvm
        cd build_scripts/macos
        ./build_all.sh